# Generated by Django 5.0.4 on 2024-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepdefinition',
            name='validation_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
