# Generated by Django 5.0.4 on 2024-04-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_alter_stepexecution_workflow_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepdefinition',
            name='engine',
            field=models.CharField(choices=[('SQL', 'SQL'), ('FUN', 'FUNCTION')], default='SQL', max_length=3),
        ),
    ]
