# Generated by Django 5.0.4 on 2024-04-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_stepdefinition_engine'),
        ('metadata', '0007_stepexecution_metadata'),
    ]

    operations = [
    ]
