# Generated by Django 5.0.4 on 2024-04-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_stepexecution_file_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepdefinition',
            options={'ordering': ['order']},
        ),
    ]
