# Generated by Django 5.0.4 on 2024-04-19 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_code', models.IntegerField()),
                ('name', models.CharField(max_length=1000)),
                ('foreign_code', models.CharField(max_length=10)),
                ('foreign_country_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('balance_report_year', models.IntegerField()),
                ('balance_row_type', models.CharField(max_length=20)),
                ('legal_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.legalperson')),
            ],
        ),
        migrations.AddField(
            model_name='legalperson',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.party'),
        ),
        migrations.CreateModel(
            name='PhysicalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=1000)),
                ('lastname', models.CharField(max_length=1000)),
                ('identification_number', models.CharField(max_length=10)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_storage.party')),
            ],
        ),
    ]
