# Generated by Django 5.0.4 on 2024-04-19 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprisegroup',
            name='company_number',
        ),
        migrations.RemoveField(
            model_name='enterprisegroup',
            name='name',
        ),
        migrations.AddField(
            model_name='enterprisegroup',
            name='group_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_group_heads', to='data_storage.party'),
        ),
        migrations.AddField(
            model_name='enterprisegroup',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_groups', to='data_storage.party'),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_type',
            field=models.CharField(choices=[('J', 'Enterprise'), ('F', 'Physical person')], max_length=1),
        ),
    ]
