# Generated by Django 5.0.4 on 2024-04-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0002_remove_enterprisegroup_company_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='value',
            new_name='assets_value',
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='foreign_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='foreign_country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='registry_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalperson',
            name='firstname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='physicalperson',
            name='identification_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='physicalperson',
            name='lastname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
