# Generated by Django 5.0.4 on 2024-04-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0003_rename_value_assets_assets_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='balance_report_year',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='balance_row_type',
        ),
    ]
