# Generated by Django 5.0.4 on 2024-04-26 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0004_remove_assets_balance_report_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprisegroup',
            name='party',
        ),
        migrations.RemoveField(
            model_name='legalperson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='physicalperson',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='physicalperson',
            name='lastname',
        ),
        migrations.AddField(
            model_name='enterprisegroup',
            name='group_nationality',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='party_uniq_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='foreign_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='registry_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='physicalperson',
            name='identification_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('child_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownerships', to='data_storage.party')),
                ('enterprise_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_storage.enterprisegroup')),
                ('parent_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_storage.party')),
            ],
        ),
    ]
