# Generated by Django 5.0.4 on 2024-04-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseGroups',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('assets_value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprises',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('assets_value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
