# Generated by Django 5.0.4 on 2024-04-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raportid', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('create role web_anon nologin;', reverse_sql='drop role web_anon;')
    ]
