# Generated by Django 5.0.4 on 2024-05-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raportid', '0002_postgrest'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE raportid_enterprises (
            id INT,
            name VARCHAR, 
            assets_value DECIMAL(20,2), 
            group_id INT, 
            share_percentage DECIMAL(10,2), 
            owner_id INT, 
            owner_name VARCHAR
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS raportid_enterprises;"
        ),
        migrations.RunSQL(
            sql="GRANT SELECT ON raportid_enterprises TO web_anon;",
            reverse_sql="REVOKE SELECT ON raportid_enterprises FROM WEB_ANON"
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE raportid_enterprisegroups (
            id INT,
            name VARCHAR, 
            assets_value DECIMAL(20,2), 
            enterprise_id INT
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS raportid_enterprisegroups;"
        ),
        migrations.RunSQL(
            sql="GRANT SELECT ON raportid_enterprisegroups TO web_anon;",
            reverse_sql="REVOKE SELECT ON raportid_enterprisegroups FROM WEB_ANON"
        ),
        migrations.RunSQL(
            sql="create index raportid_enterprisegroups_id_index on raportid_enterprisegroups (id);",
            reverse_sql=""
        ),
        migrations.RunSQL(
            sql="create index raportid_enterprisegroups_enterprise_id_index on raportid_enterprisegroups (enterprise_id);",
            reverse_sql=""
        ),
        migrations.RunSQL(
            sql="create index raportid_enterprises_id_index on raportid_enterprises (id);",
            reverse_sql=""
        ),
        migrations.RunSQL(
            sql="create index raportid_enterprises_group_id_index on raportid_enterprises (group_id);",
            reverse_sql=""
        ),
        migrations.RunSQL(
            sql="create index raportid_enterprises_owner_id_index on raportid_enterprises (owner_id);",
            reverse_sql=""
        ),
    ]
