# Generated by Django 5.0.4 on 2024-05-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raportid', '0002_postgrest'),
    ]

    operations = [
        migrations.RunSQL("""create table raportid_enterprisegroups
(
    id            integer,
    name          varchar,
    assets_value  numeric(20, 2),
    enterprise_id integer
);

create index raportid_enterprisegroups_id_index
    on raportid_enterprisegroups (id);

create index raportid_enterprisegroups_enterprise_id_index
    on raportid_enterprisegroups (enterprise_id);
""", reverse_sql='drop table raportid_enterprisegroups'),
        migrations.RunSQL("""create table raportid_enterprises
(
    id               integer,
    name             varchar,
    assets_value     numeric(20, 2),
    group_id         integer,
    share_percentage numeric(10, 2),
    owner_id         integer,
    owner_name       varchar
);

create index raportid_enterprises_id_index
    on raportid_enterprises (id);

create index raportid_enterprises_group_id_index
    on raportid_enterprises (group_id);

create index raportid_enterprises_owner_id_index
    on raportid_enterprises (owner_id);
    """, reverse_sql='drop table raportid_enterprises')
    ]
