apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rmit.fullname" . }}-backend-secret
type: Opaque
data:
  DATABASE_USER: {{ .Values.deployment.backend.database_user | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.deployment.backend.database_password | b64enc | quote }}
  DJANGO_SECRET_KEY: {{ .Values.deployment.backend.secret_key | b64enc | quote }}